stages:
  - test
  - package
  - deploy

variables:
  BACKEND_TARGET_TAG: "15-0-stable"
  POETRY_VERSION: "2.0.1"

.mr-main-release-only:
  rules:
    - if: $CI_PIPELINE_SOURCE == "push" && ($CI_COMMIT_BRANCH == "main" || $CI_COMMIT_BRANCH =~ /^v[0-9]+$/)
      variables:
        IMAGE_TAG: "${CI_COMMIT_SHA}"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      variables:
        IMAGE_TAG: "${CI_COMMIT_REF_SLUG}"

.it-tests:
  extends:
    - .mr-main-release-only
  services:
    - name: cregistry.pricefx.eu/engineering/remote-integrationtest:latest
      alias: pricefx
      variables:
        HEALTHCHECK_TCP_PORT: "2000"
  image: python:3.12
  stage: test
  interruptible: true
  variables:
    # this must be declared here for it to be visible to the service
    MY_CI_REGISTRY_PASSWORD: ${CI_REGISTRY_PASSWORD}
    PFX_BASE_URL: "http://pricefx:2000"
    PFX_SERVER_TAG: ${BACKEND_TARGET_TAG}
  script:
    - pip install poetry==${POETRY_VERSION}
    - poetry install
    # even though HEALTHCHECK_TCP_PORT is setup, compose seems to listen on the port before the service is really ready, so we need to wait here
    - timeout 300 bash -c "until curl --output /dev/null --silent $PFX_BASE_URL; do sleep 1; done"
    - poetry run pytest tests/integration -m "${MARKER_SELECTOR}"

integration-tests:
  extends:
    - .it-tests
  variables:
    MARKER_SELECTOR: "not extended"

integration-tests-extended:
  extends:
    - .it-tests
  variables:
    MARKER_SELECTOR: "extended"

tests:
  extends:
    - .mr-main-release-only
  image: python:3.12
  stage: test
  interruptible: true
  script:
    - pip install poetry==${POETRY_VERSION}
    - poetry check --lock
    - poetry install
    - poetry run flake8 pyfxlib
    - poetry run flake8 --config .flake8-tests tests
    - poetry run mypy pyfxlib --exclude _testtooling
    - poetry run pytest tests/unit

package:
  image: python:3.12
  stage: package
  interruptible: true
  script:
    - pip install poetry==${POETRY_VERSION}
    - poetry version $PACKAGE_VERSION # if defined, will replace version with $PACKAGE_VERSION
    - poetry version $(poetry version --short)$PACKAGE_VERSION_LOCAL # if defined, will replace vX with vX+branchname
    - poetry install
    - poetry build -f wheel
  artifacts:
    paths:
      - dist/
  rules:
    - if: $CI_PIPELINE_SOURCE == "push" && $CI_COMMIT_BRANCH == "main"
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      variables:
        PACKAGE_VERSION_LOCAL: "+${CI_COMMIT_REF_SLUG}"

publish-package:
  stage: deploy
  image: python:3.12
  script:
    - pip install poetry==${POETRY_VERSION}
    - poetry config repositories.pyfxlib ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/pypi
    - poetry config http-basic.pyfxlib gitlab-ci-token ${CI_JOB_TOKEN}
    - poetry version $PACKAGE_VERSION # if defined, will replace version with $PACKAGE_VERSION
    - poetry version $(poetry version --short)$PACKAGE_VERSION_LOCAL # if defined, will replace vX with vX+branchname
    - poetry publish --repository pyfxlib
  allow_failure: true
  needs:
    - package
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
      when: manual
      variables:
        PACKAGE_VERSION_LOCAL: "+${CI_COMMIT_REF_SLUG}"

######## DEPLOY DOCUMENTATION WEB #########

# Used by https://gitlab.pricefx.eu/builds/pricefx-builds/blob/master/bin%2Fbuilds-hook.sh
# DO NOT CHANGE NAME as the script above relies on it
package-pyfxlib-docs:
  stage: deploy
  image: python:3.12
  extends:
    - .mr-main-release-only
  interruptible: true
  artifacts:
    paths:
      - "./**/*.html"
  script:
    - pip install poetry==${POETRY_VERSION}
    - poetry check --lock
    - poetry install
    - poetry run pdoc3 --html --config show_source_code=False -o html --force pyfxlib
