[build-system]
requires = ["poetry_core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.black]
line-length = 100

[tool.poetry]
name = "pyfxlib"
version = "0.1.0"
description = "Python utilities for working with Pricefx"
authors = ["Pricefx"]
include = ["pyfxlib/py.typed"]
packages = [
    { include = "pyfxlib" },
    { include = "pyfxlib/_testtooling" }
]

[tool.pytest.ini_options]
markers = [
    "extended: marks extended tests, taking sometime quite a long time (deselect with '-m \"not extended\"')",
]

[tool.poetry.dependencies]
python = "3.12.*"
requests = { version = "^2.0" }

fastavro = { version = "^1.9" }
numpy = { version = ">=1.26,<3" }
pandas = { version = "^2.2" }
requests-toolbelt = { version = "^1.0" }
SecretStorage = { version = "^3.3", platform = "linux" }
setuptools = { version = "^80.0" }

[tool.poetry.group.dev.dependencies]
black = "*"
flake8 = "*"
flake8-black = "*"
isort = "*"
flake8-docstrings = "*"
mypy = "*"
pdoc3 = "0.10.*"
pep8-naming = "*"
pytest = "*"
types-requests = "^2.0"
docker = "^6.0"
types-jsonschema = "^4.21"

[tool.isort]
profile = "appnexus"
known_application=["pyfxlib"]
force_alphabetical_sort_within_sections=true

[tool.tomlsort]
ignore_case = true
in_place = true
sort_first = ["build-system", "tool.poetry"]
sort_inline_arrays = false
sort_inline_tables = false
sort_table_keys = true